### ISSUE TITLE
当 dcat-admin 更改静态资源域名后,多图上传出现跨域问题

### ISSUE THREAD

**Issue by DeadlineSurvivor** [weiaibaicai/ueditor#1]
## 环境
> php:7.4 
> laravel:7.30 
> dcat-admin:2.2.0-beta
> weiaibaicai/ueditor:1.0.2

## 问题
> 如题

![image](https://user-images.githubusercontent.com/18006395/197718619-1ea325f6-b38f-449a-910d-9844477b6dc0.png)

**Comment by weiaibaicai** [comment]
解决方案：
1. 如果可以，请不要设置静态资源域名。也就是不要设置 ADMIN_ASSETS_SERVER 或者 ASSET_URL 配置 
2. 如果配置了静态资源域名，那你就需要去修改 Nginx 配置了  (仅作参考)
```
    location / {
           add_header 'Access-Control-Allow-Origin' '*';
           add_header 'Access-Control-Allow-Credentials' 'true';
           add_header 'Access-Control-Allow-Methods' '*';
         try_files $uri $uri/ /index.php$is_args$args;
    }
```

**Comment by DeadlineSurvivor** [comment]
好的 谢谢
